# YCSB Database Comparison between MongoDB and MYSQL

## Importing Files and creating dfs

In [30]:
import pandas as pd
from matplotlib import pyplot as plt

In [31]:
files = []


# SQL file runs
files.append(('MYSQL Run A', 'outputMySQLRuna.txt'))
files.append(('MYSQL Run B', 'outputMySQLRunb.txt'))
files.append(('MYSQL Run C', 'outputMySQLRunc.txt'))
files.append(('MYSQL Run D', 'outputMySQLRund.txt'))
files.append(('MYSQL Run E', 'outputMySQLRune.txt'))
files.append(('MYSQL Run F', 'outputMySQLRunf.txt'))

# MongoDB file runs
files.append(('Mongo Run A', 'outputMongoRuna.txt'))
files.append(('Mongo Run B', 'outputMongoRunb.txt'))
files.append(('Mongo Run C', 'outputMongoRunc.txt'))
files.append(('Mongo Run D', 'outputMongoRund.txt'))
files.append(('Mongo Run E', 'outputMongoRune.txt'))
files.append(('Mongo Run F', 'outputMongoRunf.txt'))

In [32]:
# creating an empty list that will store the ycsb run dataframes
# The first row needs to be removed as its not output data

results = []
cols = ['batchSize:-1']

for name, file in files:
    # read all csvs
    df = pd.read_csv(file, skiprows=1) # here i tell it to avoid row 1 as its junk
    df.columns=[name]
    df = df.T
    df = df.drop([x for x in cols if x in df.columns], axis =1)
    results.append(df)
    
df = pd.concat(results, axis = 0)
df.head()

            Using shards: 1    [OVERALL]                       \
               batchSize:-1  RunTime(ms)  Throughput(ops/sec)
MYSQL Run A   fetchSize: -1         9356   106.88328345446772
MYSQL Run B   fetchSize: -1         4738   211.05951878429718
MYSQL Run C   fetchSize: -1         3913   255.55839509327882
MYSQL Run D   fetchSize: -1         4772   209.55574182732607
MYSQL Run E   fetchSize: -1         9459    105.7194206575748

            [TOTAL_GCS_Copy] [TOTAL_GC_TIME_Copy] [TOTAL_GC_TIME_%_Copy]  \
                       Count             Time(ms)                Time(%)
MYSQL Run A                2                   66      0.705429670799487
MYSQL Run B                2                   44     0.9286618826509077
MYSQL Run C                2                   25      0.638895987733197
MYSQL Run D                3                   31     0.6496227996647108
MYSQL Run E               19                   64     0.6766042922084787

            [TOTAL_GCS_MarkSweepCompact] [TOTAL_GC_TIME_MarkSweepCompact]  \
                                   Count                         Time(ms)
MYSQL Run A                            0                                0
MYSQL Run B                            0                                0
MYSQL Run C                            0                                0
MYSQL Run D                            0                                0
MYSQL Run E                            0                                0

            [TOTAL_GC_TIME_%_MarkSweepCompact] [TOTAL_GCs]  ...  \
                                       Time(%)       Count  ...
MYSQL Run A                                0.0           2  ...
MYSQL Run B                                0.0           2  ...
MYSQL Run C                                0.0           2  ...
MYSQL Run D                                0.0           3  ...
MYSQL Run E                                0.0          19  ...

                     [SCAN]                             \
             MaxLatency(us)  95thPercentileLatency(us)
MYSQL Run A             NaN                        NaN
MYSQL Run B             NaN                        NaN
MYSQL Run C             NaN                        NaN
MYSQL Run D             NaN                        NaN
MYSQL Run E          194687                      21567

                                                  [READ-MODIFY-WRITE]  \
             99thPercentileLatency(us)  Return=OK          Operations
MYSQL Run A                        NaN        NaN                 NaN
MYSQL Run B                        NaN        NaN                 NaN
MYSQL Run C                        NaN        NaN                 NaN
MYSQL Run D                        NaN        NaN                 NaN
MYSQL Run E                      36607        948                 NaN

                                                                 \
             AverageLatency(us)  MinLatency(us)  MaxLatency(us)
MYSQL Run A                 NaN             NaN             NaN
MYSQL Run B                 NaN             NaN             NaN
MYSQL Run C                 NaN             NaN             NaN
MYSQL Run D                 NaN             NaN             NaN
MYSQL Run E                 NaN             NaN             NaN


             95thPercentileLatency(us)  99thPercentileLatency(us)
MYSQL Run A                        NaN                        NaN
MYSQL Run B                        NaN                        NaN
MYSQL Run C                        NaN                        NaN
MYSQL Run D                        NaN                        NaN
MYSQL Run E                        NaN                        NaN

[5 rows x 52 columns]

In [33]:
# Fix the multiple indexes in df
df.columns = df.columns.map('|'.join).str.strip('|')

In [34]:
display(df.head())

,Using shards: 1| batchSize:-1,[OVERALL]| RunTime(ms),[OVERALL]| Throughput(ops/sec),[TOTAL_GCS_Copy]| Count,[TOTAL_GC_TIME_Copy]| Time(ms),[TOTAL_GC_TIME_%_Copy]| Time(%),[TOTAL_GCS_MarkSweepCompact]| Count,[TOTAL_GC_TIME_MarkSweepCompact]| Time(ms),[TOTAL_GC_TIME_%_MarkSweepCompact]| Time(%),[TOTAL_GCs]| Count,...,[SCAN]| MaxLatency(us),[SCAN]| 95thPercentileLatency(us),[SCAN]| 99thPercentileLatency(us),[SCAN]| Return=OK,[READ-MODIFY-WRITE]| Operations,[READ-MODIFY-WRITE]| AverageLatency(us),[READ-MODIFY-WRITE]| MinLatency(us),[READ-MODIFY-WRITE]| MaxLatency(us),[READ-MODIFY-WRITE]| 95thPercentileLatency(us),[READ-MODIFY-WRITE]| 99thPercentileLatency(us)
MYSQL Run A,fetchSize: -1,9356,106.88328345446772,2,66,0.705429670799487,0,0,0.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MYSQL Run B,fetchSize: -1,4738,211.05951878429718,2,44,0.9286618826509077,0,0,0.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MYSQL Run C,fetchSize: -1,3913,255.55839509327882,2,25,0.638895987733197,0,0,0.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MYSQL Run D,fetchSize: -1,4772,209.55574182732607,3,31,0.6496227996647108,0,0,0.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MYSQL Run E,fetchSize: -1,9459,105.7194206575748,19,64,0.6766042922084787,0,0,0.0,19,...,194687,21567,36607,948,NaN,NaN,NaN,NaN,NaN,NaN

## Renaming the relevant columns for plotting

In [35]:
df.rename(columns={'[OVERALL]| RunTime(ms)': 'Overall_Runtime'}, inplace=True)
df.rename(columns={'[READ]| Operations': 'read_throughputOps'}, inplace=True)
df.rename(columns={'[READ]| AverageLatency(us)': 'read_latency'}, inplace=True)
df.rename(columns={'[UPDATE]| Operations': 'update_throughputOps'}, inplace=True)
df.rename(columns={'[UPDATE]| AverageLatency(us)': 'update_latency'}, inplace=True)
df.rename(columns={'[SCAN]| Operations': 'scan_throughputOps'}, inplace=True)
df.rename(columns={'[SCAN]| AverageLatency(us)': 'scan_latency'}, inplace=True)
df.rename(columns={'[INSERT]| Operations': 'insert_throughputOps'}, inplace=True)
df.rename(columns={'[INSERT]| AverageLatency(us)': 'insert_latency'}, inplace=True)
df.rename(columns={'[READ-MODIFY-WRITE]| Operations': 'read_modify_write_throughputOps'}, inplace=True)
df.rename(columns={'[READ-MODIFY-WRITE]| AverageLatency(us)': 'read_modify_write_latency'}, inplace=True)

In [36]:
df.columns

Index(['Using shards: 1| batchSize:-1', 'Overall_Runtime',
       '[OVERALL]| Throughput(ops/sec)', '[TOTAL_GCS_Copy]| Count',
       '[TOTAL_GC_TIME_Copy]| Time(ms)', '[TOTAL_GC_TIME_%_Copy]| Time(%)',
       '[TOTAL_GCS_MarkSweepCompact]| Count',
       '[TOTAL_GC_TIME_MarkSweepCompact]| Time(ms)',
       '[TOTAL_GC_TIME_%_MarkSweepCompact]| Time(%)', '[TOTAL_GCs]| Count',
       '[TOTAL_GC_TIME]| Time(ms)', '[TOTAL_GC_TIME_%]| Time(%)',
       'read_throughputOps', 'read_latency', '[READ]| MinLatency(us)',
       '[READ]| MaxLatency(us)', '[READ]| 95thPercentileLatency(us)',
       '[READ]| 99thPercentileLatency(us)', '[READ]| Return=OK',
       '[CLEANUP]| Operations', '[CLEANUP]| AverageLatency(us)',
       '[CLEANUP]| MinLatency(us)', '[CLEANUP]| MaxLatency(us)',
       '[CLEANUP]| 95thPercentileLatency(us)',
       '[CLEANUP]| 99thPercentileLatency(us)', 'update_throughputOps',
       'update_latency', '[UPDATE]| MinLatency(us)',
       '[UPDATE]| MaxLatency(us)', '[UPDATE]| 95thPercentileLatency(us)',
       '[UPDATE]| 99thPercentileLatency(us)', '[UPDATE]| Return=OK',
       'insert_throughputOps', 'insert_latency', '[INSERT]| MinLatency(us)',
       '[INSERT]| MaxLatency(us)', '[INSERT]| 95thPercentileLatency(us)',
       '[INSERT]| 99thPercentileLatency(us)', '[INSERT]| Return=OK',
       'scan_throughputOps', 'scan_latency', '[SCAN]| MinLatency(us)',
       '[SCAN]| MaxLatency(us)', '[SCAN]| 95thPercentileLatency(us)',
       '[SCAN]| 99thPercentileLatency(us)', '[SCAN]| Return=OK',
       'read_modify_write_throughputOps', 'read_modify_write_latency',
       '[READ-MODIFY-WRITE]| MinLatency(us)',
       '[READ-MODIFY-WRITE]| MaxLatency(us)',
       '[READ-MODIFY-WRITE]| 95thPercentileLatency(us)',
       '[READ-MODIFY-WRITE]| 99thPercentileLatency(us)'],
      dtype='object')

df.plot(subplots=True, layout=(1,2))

In [38]:
# creation of separate dataframes for plotting

dfa = pd.DataFrame.loc[df['workloadA'].str.contains('Run A', case=False)]
dfb = ppd.DataFrame.loc[df['workloadB'].str.contains('Run B', case=False)]
dfc = pd.DataFrame.loc[df['workloadC'].str.contains('Run C', case=False)]
dfd = pd.DataFrame.loc[df['workloadD'].str.contains('Run D', case=False)]
dfe = pd.DataFrame.loc[df['workloadE'].str.contains('Run F', case=False)]
dff = pd.DataFrame.loc[df['workloadF'].str.contains('Run G', case=False)]

KeyError: 'workloadA'

In [ ]:
dfa = df.loc[df['RunTime'].str.contains('Run A', case=False)]
dfb = df.loc[df['RunTime'].str.contains('Run B', case=False)]
dfc = df.loc[df['RunTime'].str.contains('Run C', case=False)]
dfd = df.loc[df['RunTime'].str.contains('Run D', case=False)]
dfe = df.loc[df['RunTime'].str.contains('Run F', case=False)]
dff = df.loc[df['RunTime'].str.contains('Run G', case=False)]